version: "3.6"

services:
  proxy:
    image: betalabs/nginx-basic-auth-proxy
    environment:
      - BASIC_AUTH_USERNAME=${settings.basic_auth.username}
      - BASIC_AUTH_PASSWORD=${settings.basic_auth.password}
      - PORT=80
      - UPSTREAM_URL=http://viz:8080/
    ports:
      - ${settings.port}:80
    deploy:
      labels:
        - com.docker.aws.lb.arn=${settings.acm_certificate_arn}@HTTPS:${settings.port}
      placement:
        constraints:
          - node.role == worker
  viz:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  default:
    driver: overlay

